name: Build and deploy App Service

on:
  workflow_dispatch: {}
  push:
    paths-ignore:
      - "src/Bz.Fott.Registration.NumberAssignatorAzFunction/**"
      - ".github/workflows/build-and-deploy-functionapp.yml"

env:
  AZURE_WEBAPP_NAME: ${{ vars.AZURE_WEBAPP_NAME }}
  AZURE_WEBAPP_PACKAGE_PATH: publish
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 7.0.x
  WORKING_DIRECTORY: .

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}/src/Bz.Fott.Registration.WebAPI/"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}/src/Bz.Fott.Registration.WebAPI/" --configuration ${{ env.CONFIGURATION }} --no-restore
    #- name: Test
    #  run: dotnet test "${{ env.WORKING_DIRECTORY }}/test/" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}/src/Bz.Fott.Registration.WebAPI/" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}